import argparse
import json
from pathlib import Path
from typing import Dict, List, Set, Tuple


ALL_TEXT_CATEGORIES = {
    "Text",
    "Title",
    "Section-header",
    "Caption",
    "Footnote",
    "List-item",
    "Page-header",
    "Page-footer",
    "Table",
}

CORE_TEXT_CATEGORIES = {
    "Text",
    "Title",
    "Section-header",
    "List-item",
    "Page-header",
    "Page-footer",
}


def collect_confidences_from_single_output(
    data: Dict, selected_categories: Set[str]
) -> Tuple[List[float], Dict[str, List[float]]]:
    layout_elements = data.get("layout_elements", [])
    confidences: List[float] = []
    by_category: Dict[str, List[float]] = {}

    for element in layout_elements:
        category = element.get("category", "Unknown")
        confidence = float(element.get("ocr_confidence", 0.0) or 0.0)
        if category in selected_categories and confidence > 0:
            confidences.append(confidence)
            by_category.setdefault(category, []).append(confidence)
    return confidences, by_category


def collect_confidences_from_batch_output(
    data: Dict, selected_categories: Set[str]
) -> Tuple[List[float], Dict[str, List[float]]]:
    documents = data.get("documents", [])
    confidences: List[float] = []
    by_category: Dict[str, List[float]] = {}

    for document in documents:
        for element in document.get("elements", []):
            category = element.get("category", "Unknown")
            confidence = float(element.get("confidence", 0.0) or 0.0)
            if category in selected_categories and confidence > 0:
                confidences.append(confidence)
                by_category.setdefault(category, []).append(confidence)
    return confidences, by_category


def aggregate(
    paths: List[Path], selected_categories: Set[str]
) -> Tuple[List[float], Dict[str, List[float]]]:
    all_confidences: List[float] = []
    category_map: Dict[str, List[float]] = {}

    for path in paths:
        if not path.exists():
            continue

        data = json.loads(path.read_text(encoding="utf-8"))
        if "layout_elements" in data:
            confidences, by_category = collect_confidences_from_single_output(
                data, selected_categories
            )
        elif "documents" in data:
            confidences, by_category = collect_confidences_from_batch_output(
                data, selected_categories
            )
        else:
            continue

        all_confidences.extend(confidences)
        for category, values in by_category.items():
            category_map.setdefault(category, []).extend(values)

    return all_confidences, category_map


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Compute OCR accuracy proxy from saved IDP JSON outputs."
    )
    parser.add_argument(
        "--files",
        nargs="*",
        default=[
            "output/idp_output_1.json",
            "output/idp_batch_output.json",
        ],
        help="Output JSON files generated by your pipeline.",
    )
    parser.add_argument(
        "--threshold",
        type=float,
        default=0.5,
        help="Confidence threshold to count predictions as 'correct' (default: 0.5).",
    )
    parser.add_argument(
        "--profile",
        type=str,
        choices=["core-text", "all-text"],
        default="core-text",
        help=(
            "Category profile for evaluation. "
            "core-text focuses on primary reading regions; "
            "all-text includes caption/table/footnote as well."
        ),
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    paths = [Path(p) for p in args.files]
    selected_categories = (
        CORE_TEXT_CATEGORIES if args.profile == "core-text" else ALL_TEXT_CATEGORIES
    )
    confidences, category_map = aggregate(paths, selected_categories)

    existing_files = [str(p) for p in paths if p.exists()]
    if not existing_files:
        print("No output JSON files found.")
        print("Run your pipeline first, then rerun this script.")
        return 1

    if not confidences:
        print("No text OCR confidence values found in provided files.")
        return 1

    mean_confidence = sum(confidences) / len(confidences)
    threshold_hits = sum(1 for c in confidences if c >= args.threshold)
    threshold_accuracy = threshold_hits / len(confidences)

    print("=== OCR Accuracy Report (Proxy Metric) ===")
    print(f"Profile: {args.profile}")
    print(f"Files used: {', '.join(existing_files)}")
    print(f"Text regions evaluated: {len(confidences)}")
    print(f"Mean OCR confidence: {mean_confidence:.4f}")
    print(f"OCR confidence accuracy (%): {mean_confidence * 100:.2f}")
    print(
        f"Threshold accuracy @ {args.threshold:.2f}: "
        f"{threshold_accuracy * 100:.2f}% ({threshold_hits}/{len(confidences)})"
    )

    print("\nPer-category confidence:")
    for category in sorted(category_map):
        values = category_map[category]
        avg = sum(values) / len(values)
        print(f"- {category:<16} count={len(values):>4} mean={avg:.4f}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
